### ISSUE TITLE
BUG: Filter pointer 

### ISSUE THREAD

**Issue by Nozgood** [ulphidius/iterago#57]
When We use iterago.Filter(), in a certain condition, one value can be append in the orignal slice that is verified 

I use time pointer in the condition 

```go
	value := iterago.Filter(
		test.Statistics,
		func(stat *exchange.Statistic) bool {
			verification := stat.Date.AsTime().Before(u.clock.Now().UTC().Truncate(time.Duration(unitTime)*time.Hour)) ||
				(stat.IsForecastStatistic &&
					stat.Date.AsTime() == u.clock.Now().UTC().Truncate(time.Duration(utils.UnitTimeDay)*time.Hour))
			return verification
		})
```

**Comment by ulphidius** [comment]
Hello, thanks for you feedback.
May i know what the type of the **Date**, **clock** and **unitTime** are ?
And may i know what is the value of **unitTime** is ?

**Comment by Nozgood** [comment]
> Hello, thanks for you feedback. May i know what the type of the **Date**, **clock** and **unitTime** are ? And may i know what is the value of **unitTime** is ?

Hello yes :
- type of clock : time.Time
- Date: time.Time
- UnitTime: int64 and it value can be 1 or 24 but in the case where the bug come UnitTime has 24 value

**Comment by ulphidius** [comment]
I failed to reproduce the bug.
Perhaps you can give more context please ?
